//! OpenCode client: MCP in `opencode.json(c)` plus one in-process plugin.

use super::Ctx;

const PLUGIN: &str = include_str!("../../skill/opencode.js");

pub(crate) fn opencode(c: &Ctx) -> Result<(), String> {
    let dir = c.home.join(".config/opencode");
    let path = ["opencode.jsonc", "opencode.json"]
        .iter()
        .map(|n| dir.join(n))
        .find(|p| p.is_file())
        .unwrap_or_else(|| dir.join("opencode.json"));
    let old = std::fs::read_to_string(&path).unwrap_or_else(|_| "{}\n".into());
    let mut s = old.clone();
    let mut what = vec![];
    // ponytail: JSONC edited as text so comments survive. The probes are
    // substring checks — a key named "fael"/"mcp" inside a comment fools them.
    if s.contains("\"fael\":") {
        println!("  mcp fael already set");
    } else {
        let exe = serde_json::to_string(&c.exe).map_err(|e| e.to_string())?;
        let entry = format!("\"fael\": {{\"type\": \"local\", \"command\": [{exe}, \"mcp\"]}}");
        s = match s.find("\"mcp\"") {
            Some(i) => insert_first(&s, i, &entry),
            None => insert_first(&s, 0, &format!("\"mcp\": {{{entry}}}")),
        }
        .ok_or(format!(
            "{}: no JSON object to add mcp.fael to",
            path.display()
        ))?;
        what.push("mcp.fael");
    }
    const OFF: &str = "\"fapony\": {\"enabled\": false,";
    if let Some(i) = s.find("\"fapony\": {").filter(|_| !s.contains(OFF)) {
        if c.replace {
            s.replace_range(i..i + "\"fapony\": {".len(), OFF);
            what.push("disabled mcp.fapony");
        } else {
            println!(
                "  ! mcp.fapony is still on in {} — --replace-fapony disables it",
                path.display()
            );
        }
    }
    if s != old {
        c.write(&path, &s)?;
        c.say(&what.join(", "), &path);
    }
    // fapony's session-start plugin is the only one that competes (OpenCode has
    // no Stop): disable by rename, never delete
    let fp = dir.join("plugins/fapony-session-start.ts");
    if fp.is_file() {
        if c.replace {
            if !c.dry {
                std::fs::rename(&fp, fp.with_extension("ts.disabled"))
                    .map_err(|e| e.to_string())?;
            }
            println!(
                "  {} {} → .disabled",
                if c.dry { "would rename" } else { "renamed" },
                fp.display()
            );
        } else {
            println!(
                "  ! {} still runs — --replace-fapony disables it",
                fp.display()
            );
        }
    }
    let plugin = dir.join("plugins/fael.js");
    let body = PLUGIN.replace(
        "__FAEL__",
        &serde_json::to_string(&c.exe).map_err(|e| e.to_string())?,
    );
    match std::fs::read_to_string(&plugin) {
        Ok(cur) if cur == body => println!("  plugin already set"),
        Ok(cur) if !cur.starts_with("// fael — generated by `fael install`") => {
            println!("  ! {} is not fael's — left alone", plugin.display());
        }
        _ => {
            c.write(&plugin, &body)?;
            c.say("plugin (stop/session-start/read/edit)", &plugin);
        }
    }
    Ok(())
}

/// Put `entry` right after the first `{` at or after `from`, with a comma
/// only when the object is not empty.
fn insert_first(s: &str, from: usize, entry: &str) -> Option<String> {
    let brace = from + s[from..].find('{')? + 1;
    let empty = s[brace..].trim_start().starts_with('}');
    let comma = if empty { "" } else { "," };
    Some(format!("{}\n  {entry}{comma}{}", &s[..brace], &s[brace..]))
}

#[cfg(test)]
mod tests {
    use super::insert_first;

    #[test]
    fn jsonc_insert() {
        assert_eq!(insert_first("{}", 0, "\"k\": 1").unwrap(), "{\n  \"k\": 1}");
        assert_eq!(
            insert_first("{ // c\n \"mcp\": { \"x\": {} } }", 8, "\"k\": 1").unwrap(),
            "{ // c\n \"mcp\": {\n  \"k\": 1, \"x\": {} } }"
        );
        assert!(insert_first("[]", 0, "x").is_none());
    }
}
